# .streamlit/config.toml

[theme]
primaryColor              = "#39FF14"    # Neon-green accent
backgroundColor           = "#0D0D0D"    # Nearly black
secondaryBackgroundColor  = "#1A1A1A"    # Dark panels
textColor                 = "#F0F0F0"    # Soft white text
font                      = "sans serif"


[server]
headless = true

[ui]
hide_sidebar_nav = false

[pages]
show_home_in_sidebar = false
