# .streamlit/config.toml

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"  # Options: "sans serif", "serif", "monospace"


[server]
headless = true

[ui]
hide_sidebar_nav = false

[pages]
show_home_in_sidebar = false
